//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_To
    {
        public C_To()
        {
            this.C_LoaiTo = new HashSet<C_LoaiTo>();
            this.C_ThongTinNguoiLaoDong = new HashSet<C_ThongTinNguoiLaoDong>();
        }
    
        public string C_MaTo { get; set; }
        public string C_MaDoi { get; set; }
        public string C_TenTo { get; set; }
    
        public virtual C_Doi C_Doi { get; set; }
        public virtual ICollection<C_LoaiTo> C_LoaiTo { get; set; }
        public virtual ICollection<C_ThongTinNguoiLaoDong> C_ThongTinNguoiLaoDong { get; set; }
    }
}
