//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMNS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Doi
    {
        public C_Doi()
        {
            this.C_ThongTinNguoiLaoDong = new HashSet<C_ThongTinNguoiLaoDong>();
            this.C_To = new HashSet<C_To>();
        }
    
        public string C_MaDoi { get; set; }
        public string C_MaPhong { get; set; }
        public string C_TenDoi { get; set; }
    
        public virtual C_Phong C_Phong { get; set; }
        public virtual ICollection<C_ThongTinNguoiLaoDong> C_ThongTinNguoiLaoDong { get; set; }
        public virtual ICollection<C_To> C_To { get; set; }
    }
}
