//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMNS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_LoaiTo
    {
        public C_LoaiTo()
        {
            this.C_ThongTinNguoiLaoDong = new HashSet<C_ThongTinNguoiLaoDong>();
        }
    
        public string C_MaLoaiTo { get; set; }
        public string C_MaTo { get; set; }
        public string C_TenLoaiTo { get; set; }
    
        public virtual C_To C_To { get; set; }
        public virtual ICollection<C_ThongTinNguoiLaoDong> C_ThongTinNguoiLaoDong { get; set; }
    }
}
