//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMNS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Phong
    {
        public C_Phong()
        {
            this.C_Doi = new HashSet<C_Doi>();
            this.C_ThongTinNguoiLaoDong = new HashSet<C_ThongTinNguoiLaoDong>();
        }
    
        public string C_MaPhong { get; set; }
        public string C_TenPhong { get; set; }
    
        public virtual ICollection<C_Doi> C_Doi { get; set; }
        public virtual ICollection<C_ThongTinNguoiLaoDong> C_ThongTinNguoiLaoDong { get; set; }
    }
}
