//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMNS.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NhanSuTCDEntities : DbContext
    {
        public NhanSuTCDEntities()
            : base("name=NhanSuTCDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Doi> C_Doi { get; set; }
        public virtual DbSet<C_LoaiTo> C_LoaiTo { get; set; }
        public virtual DbSet<C_Phong> C_Phong { get; set; }
        public virtual DbSet<C_ThanhPho> C_ThanhPho { get; set; }
        public virtual DbSet<C_ThongTinGiaDinh> C_ThongTinGiaDinh { get; set; }
        public virtual DbSet<C_ThongTinHopDongLaoDong> C_ThongTinHopDongLaoDong { get; set; }
        public virtual DbSet<C_ThongTinKhenThuong> C_ThongTinKhenThuong { get; set; }
        public virtual DbSet<C_ThongTinKyLuat> C_ThongTinKyLuat { get; set; }
        public virtual DbSet<C_ThongTinNguoiLaoDong> C_ThongTinNguoiLaoDong { get; set; }
        public virtual DbSet<C_ThongTinTrinhDo> C_ThongTinTrinhDo { get; set; }
        public virtual DbSet<C_To> C_To { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TD_DD_BN_TV> TD_DD_BN_TV { get; set; }
    }
}
